# Generated by Django 2.2 on 2020-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_auto_20200715_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
