# Generated by Django 2.2 on 2020-07-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_remove_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, default='productImages/no_img.png', upload_to='productImages', verbose_name='تصویر'),
        ),
    ]
